// <auto-generated />
using System;
using InventoryManagerDemo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InventoryManagerDemo.Database.Migrations
{
    [DbContext(typeof(InventoryManagerContext))]
    [Migration("20190327213723_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InventoryManagerDemo.Database.Models.Pallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsPlaced");

                    b.Property<int?>("SizeId");

                    b.Property<decimal>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("SizeId");

                    b.ToTable("Pallets");
                });

            modelBuilder.Entity("InventoryManagerDemo.Database.Models.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Heigh");

                    b.Property<int>("Length");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("InventoryManagerDemo.Database.Models.Stillage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FreeSpaces");

                    b.Property<decimal>("MaximumLoad");

                    b.Property<int?>("SizeId");

                    b.HasKey("Id");

                    b.HasIndex("SizeId");

                    b.ToTable("Stillages");
                });

            modelBuilder.Entity("InventoryManagerDemo.Database.Models.Pallet", b =>
                {
                    b.HasOne("InventoryManagerDemo.Database.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId");
                });

            modelBuilder.Entity("InventoryManagerDemo.Database.Models.Stillage", b =>
                {
                    b.HasOne("InventoryManagerDemo.Database.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId");
                });
#pragma warning restore 612, 618
        }
    }
}
